### ISSUE TITLE
Are you ok?

### ISSUE THREAD

**Issue by siddharthroy12** [Benjimanrich/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA#3]
What the hell is inside that file?

**Comment by osmanmesutozcan** [comment]
It is a wav file. I played it (which I probably not supposed to) and it sounds backwards.

**Comment by Benjimanrich** [comment]
lol this was just a joke don't worry
